proxy:
    path: /proxy
    controller: App\Controller\DefaultController:proxyAction

api:
  prefix: /api/v1
  resource: "../../src/Controller/Api"
  type: annotation

catch_all:
    path: "{catchAll}"
    controller: App\Controller\DefaultController:indexAction
    requirements:
        catchAll: ".*"

